{% set version = "0.4.13" %}

package:
  name: ruamel.ordereddict
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/ruamel.ordereddict/ruamel.ordereddict-{{ version }}.tar.gz
  sha256: bf0a198c8ce5d973c24e5dba12d3abc254996788ca6ad8448eabc6aa710db149

build:
  number: 1
  skip: True  # [py3k]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - ruamel.ordereddict

about:
  home: https://bitbucket.org/ruamel/ordereddict
  license: MIT
  license_file: LICENSE
  summary: "a version of dict that keeps keys in insertion resp. sorted order"

extra:
  recipe-maintainers:
    - pelson
    - mwcraig
    - ocefpaf
