travis:
  secure:
    BINSTAR_TOKEN: PrrBDe2C97WYRAMyZzkKnkE7uMLo7xJq5bePOhRXvZOF5yldUN1k6s4eJ0hQPB0N709EchqqfbkTfxsJfNMV4VLA1qHehZpc9fCrPr+61Gp2k9OjMxwGtxAIt4cikJxKAYoV/MxkTi0AhImp88gCkfoHql4rwpNeDcB831o+qKFKMjwCcCGLAj04+CN6KHIvEckNkwh4ohq9N8mE8eXj2Xm7RhjU93BF8556dOi7dJr/8fD4fkKGBNj/DzI2rDB8nCD+sX0a4xtbfbtTfIx38+biLqwFRTHO7WfxUN8Uo7+lxHtHyNkcjsLIwZcLACyKKlose84pjr2NsNz9JJmRElbdArFBiMSuv2ky+3lkclJ0iLjwBPpqsIPADGdbdywu2gMS+8dGIZLuY1NJtN0s6/NQo7EC6svEFeqWU5eaa3v/DgxzxfDDhoPGx7k4DJNPZqLJNZ9pV7CoSsCwTeaZB6lxSVqcw0hFui/741o0DiT6kEXf8VmHYkpf5cYJd/OXVt6ZxvkJ8AiW0gJqfTxn9agGQn7zScdB3TR/WgGlEv9kceTzedvLWW+iM1IHnXnzm74wsqwecUmxR8AY+hcjQjkkA+SF4kOqyR16RhYwiDtkReZZLl5PPuFo6ffM5EB8omWN8hQe5Xv4pf41iIAKntClPS2xgeDtkVyaqpSqSQw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
